export const it = {
  app: {
    name: "MarkGuardiola",
    tagline: "Decisioni di Fantacalcio per la tua rosa",
    skipToContent: "Salta al contenuto",
    loading: "Caricamento…",
    retry: "Riprova",
    cancel: "Annulla",
    close: "Chiudi",
    save: "Salva",
    edit: "Modifica",
    confirm: "Conferma",
    back: "Indietro",
    next: "Avanti",
    notAvailable: "n/d",
    error: "Qualcosa è andato storto",
    errorBody:
      "La richiesta non è andata a buon fine. Controlla che il servizio locale sia attivo e riprova.",
    offline: "Il servizio locale non risponde. Verifica che l'API sia avviata.",
    requestCancelled: "Richiesta annullata.",
  },

  nav: {
    giornata: "Giornata",
    rosa: "La mia rosa",
    rosaShort: "Rosa",
    mercato: "Mercato",
    giocatori: "Giocatori",
    lega: "Lega",
  },

  status: {
    degraded: "Alcuni calcoli non sono disponibili.",
    degradedLink: "Apri Sistema",
    dismiss: "Nascondi avviso",
  },

  benvenuto: {
    title: "Benvenuto",
    kicker: "Il tuo mister per la domenica",
    intro:
      "MarkGuardiola confronta le prossime partite per scegliere formazione, panchina e acquisti. Inizia dalla tua lega.",
    createTitle: "La tua lega",
    nameLabel: "Nome della lega",
    namePlaceholder: "Es. Lega degli amici",
    modeLabel: "Modalità",
    modeClassic: "Classic",
    modeClassicDesc: "Ruoli P, D, C, A e moduli tradizionali.",
    modeMantra: "Mantra",
    modeMantraDesc: "Ruoli di campo dettagliati (Por, Dc, E, T, Pc…).",
    creditsLabel: "Crediti totali",
    teamNameLabel: "Nome della tua squadra",
    coachNameLabel: "Nome dell'allenatore",
    h2hLabel: "Scontri testa a testa",
    h2hHint: "Attivalo se la tua lega prevede sfide dirette con classifica.",
    submit: "Crea la lega",
    creating: "Creo la lega…",
    createdTitle: "Lega creata",
    rulesReviewIntro: "Queste sono le regole di partenza. Puoi cambiarle in Lega, sezione Regole.",
    goImport: "Importa la rosa",
    goGiornata: "Vai alla Giornata",
  },

  leghe: {
    title: "Le tue leghe",
    pickIntro: "Scegli la lega con cui lavorare.",
    open: "Apri",
    newLeague: "Nuova lega",
    empty: "Nessuna lega salvata.",
    mode: { classic: "Classic", mantra: "Mantra" },
    h2hOn: "Testa a testa",
    switchLeague: "Cambia lega",
  },

  giornata: {
    title: "Giornata",
    formationBoard: "La formazione",
    recommended: "consigliata",
    riskLabel: "Impostazione",
    riskBalanced: "Equilibrata",
    riskFloor: "Prudente",
    riskUpside: "Offensiva",
    riskBalancedLong: "Equilibrata, punta sulla stima centrale",
    riskFloorLong: "Prudente, protegge lo scenario peggiore",
    riskUpsideLong: "Offensiva, cerca il potenziale",
    recalc: "Ricalcola",
    benchBoard: "Panchina",
    benchOrderHint: "In ordine di ingresso consigliato.",
    scoreBoard: "Punteggio atteso",
    scoreCenter: "stima centrale",
    scoreRangeHint: "Nella maggior parte degli scenari il totale cade qui.",
    confidence: "Affidabilità",
    substitutions: "Cambi attesi",
    modifier: "Modificatore atteso",
    whyBoard: "Perché",
    warningsBoard: "Avvertenze",
    computing: "Sto simulando le prossime partite",
    computingBody:
      "La prima volta il calcolo completo può richiedere fino a un minuto. Le volte successive è quasi immediato.",
    elapsed: "in corso da",
    matchupBoard: "Scontro diretto",
    matchupOpponent: "Avversario",
    matchupRun: "Simula lo scontro",
    matchupRunning: "Simulo lo scontro…",
    win: "Vittoria",
    draw: "Pareggio",
    loss: "Sconfitta",
    matchupFormation: "Formazione ottimizzata per lo scontro",
    matchupNoOpponents: "Non ci sono rose avversarie. Aggiungile in Lega, sezione Squadre.",
    utility: "utilità",
    presence: "presenza",
    points: "punti",
    advanced: "Dettagli avanzati",
    optimality: "Il risultato dipende dagli scenari analizzati.",
    freshnessData: "Dati calcolati al",
    freshnessDecision: "Disponibilità aggiornate al",
    emptyRosterTitle: "Manca la rosa",
    emptyRosterBody:
      "Per consigliarti la formazione serve prima la tua rosa. Importala incollando l'elenco dei tuoi giocatori.",
    emptyRosterCta: "Importa la rosa",
    emptyPredictionsTitle: "Previsioni non disponibili",
    emptyPredictionsBody: "Non ci sono previsioni per le prossime partite. Aggiorna i dati in Lega, sezione Sistema.",
    emptyPredictionsCta: "Vai al sistema",
    emptyFormationTitle: "Nessuna formazione schierabile",
    emptyFormationBody:
      "Con i ruoli attuali la rosa non riempie nessun modulo previsto dalla lega. Controlla i ruoli in rosa o le regole della lega.",
    emptyFormationCta: "Vedi la rosa",
  },

  rosa: {
    title: "La mia rosa",
    boardTitle: "Organico",
    validationBoard: "Composizione da sistemare",
    validationIntro: "I vincoli controllano la composizione della rosa.",
    validationDraftNote: "Una rosa in costruzione può stare sotto il minimo. I limiti massimi restano attivi.",
    playerCount: (n: number) => (n === 1 ? "1 giocatore" : `${n} giocatori`),
    budget: "Crediti residui",
    budgetOf: "su",
    budgetEdit: "Aggiorna crediti",
    budgetSaved: "Crediti aggiornati.",
    budgetInvalid: "Inserisci un numero valido, ad esempio 75,5.",
    reimport: "Reimporta la rosa",
    priceUnknown: "prezzo non disponibile",
    inactive: "fuori rosa",
    emptyTitle: "Rosa vuota",
    emptyBody: "Incolla nome, ruolo, squadra e prezzo dei tuoi giocatori.",
    emptyCta: "Importa la rosa",
    countOf: (n: number, max: number | null, role: string) =>
      max === null ? `${n} ${role}` : `${n} di ${max} ${role}`,
    previousRole: (role: string) => `Scorri indietro: ${role}`,
    nextRole: (role: string) => `Scorri avanti: ${role}`,
    roleNames: {
      GK: "Portieri",
      DEF: "Difensori",
      MID: "Centrocampisti",
      FWD: "Attaccanti",
      other: "Altri ruoli",
    } as Record<string, string>,
  },

  imports: {
    rosterTitle: "Importa la rosa",
    marketTitle: "Importa gli svincolati",
    opponentTitle: "Importa una rosa avversaria",
    stepPaste: "Incolla",
    stepReview: "Controlla",
    stepResolve: "Risolvi",
    stepDone: "Fatto",
    pasteLabel: "Elenco giocatori",
    pastePlaceholder:
      "Un giocatore per riga. Es.\nMartinez L., A, Inter, 36\nDi Lorenzo, D, Napoli, 15",
    pasteHelp: "Formato accettato",
    pasteHelpBody:
      "Usa una riga per giocatore. Separa i campi con virgola, tabulazione oppure punto e virgola. Ordine dei campi: nome, ruolo, squadra e prezzo. Il prezzo è facoltativo. Usa le virgolette se un campo contiene un separatore. Ruoli Classic: P, D, C, A. Ruoli Mantra: Por, Dd, Ds, Dc, B, E, M, C, W, T, A, Pc. Per più ruoli usa la barra, per esempio W/A. Limite file: 2 MiB.",
    fileButton: "…oppure carica un file CSV",
    fileReading: "Leggo il file…",
    fileReadError: "Non riesco a leggere il file. Riprova oppure incolla l’elenco.",
    opponentNameLabel: "Nome della squadra avversaria",
    creditsOptionalLabel: "Crediti residui (facoltativo)",
    parsedRows: (n: number) => (n === 1 ? "1 riga letta" : `${n} righe lette`),
    parseIssues: "Righe da controllare",
    emptyParse: "Nessuna riga riconosciuta. Controlla il formato.",
    replaceWarningRoster:
      "La rosa attuale verrà sostituita dall'elenco che stai importando.",
    replaceWarningMarket:
      "Il listone attuale verrà sostituito dall'elenco che stai importando.",
    send: "Invia e riconosci i nomi",
    sending: "Riconosco i nomi…",
    reviewTitle: "Righe lette",
    name: "Nome",
    role: "Ruolo",
    team: "Squadra",
    price: "Prezzo",
    resolveIntro:
      "Controlla i riconoscimenti: scegli tu nei casi ambigui. Le righe non riconosciute restano visibili e non vengono inventate.",
    resolvedBadge: "riconosciuto",
    ambiguousBadge: "da scegliere",
    unresolvedBadge: "non riconosciuto",
    ambiguousPick: "Scegli il giocatore corretto",
    unresolvedKeep:
      "Nessuna corrispondenza affidabile. Correggi il nome e reinvia, oppure escludi la riga.",
    excludeRow: "Escludi dalla rosa",
    excludedNote: "esclusa",
    confidence: "affidabilità",
    confirmFinal: "Conferma la rosa completa",
    confirmFinalMarket: "Conferma il listone",
    confirmFinalHint: (resolved: number, excluded: number) => {
      const saved =
        resolved === 1
          ? "Verrà salvato 1 giocatore"
          : `Verranno salvati ${resolved} giocatori`;
      if (excluded === 0) return `${saved}.`;
      const left =
        excluded === 1
          ? "1 riga resta esclusa per tua scelta"
          : `${excluded} righe restano escluse per tua scelta`;
      return `${saved}. ${left}.`;
    },
    pendingChoices: (n: number) =>
      n === 1
        ? "Resta 1 riga da risolvere o escludere."
        : `Restano ${n} righe da risolvere o escludere.`,
    doneTitle: "Importazione completata",
    doneRoster: (n: number) => `La rosa ora conta ${n} giocatori.`,
    doneMarket: (n: number) => `Il listone ora conta ${n} giocatori.`,
    partialWarning: (n: number) =>
      n === 1
        ? "1 riga non è stata salvata: non era stata riconosciuta."
        : `${n} righe non sono state salvate: non erano state riconosciute.`,
    goGiornata: "Vai alla Giornata",
    goRosa: "Vedi la rosa",
    goMercato: "Vai al Mercato",
  },

  aggiungi: {
    rosterTitle: "Aggiungi un giocatore",
    opponentTitle: "Aggiungi a una rosa avversaria",
    marketTitle: "Aggiungi uno svincolato",
    entryRoster: "Aggiungi giocatore",
    entryMarket: "Aggiungi svincolato",
    intro:
      "Cerca un giocatore reale per nome e aggiungilo senza toccare il resto dell'elenco.",
    searchBoard: "Ricerca",
    searchLabel: "Cerca il giocatore",
    searchPlaceholder: "Nome o cognome…",
    searchEmptyTitle: "Nessun giocatore trovato",
    searchEmptyBody: "Prova con una parte del cognome.",
    searchErrorBody: "La ricerca non ha risposto. Riprova.",
    pick: "Scegli",
    selectedLabel: "Giocatore scelto",
    changeSelection: "Cambia giocatore",
    rolesLabel: "Ruoli di lega",
    rolesPrimaryHint: "Il primo ruolo scelto è quello principale per il punteggio.",
    rolesReplaceWarning:
      "I ruoli indicati sostituiscono per intero i ruoli di lega del giocatore, in tutte le rose che lo contengono.",
    rolesKeep: "Lascia i ruoli attuali",
    rolesKeepHint: "Senza ruoli espliciti restano quelli registrati. Per un giocatore nuovo devi scegliere il ruolo.",
    rolesMantraRequired:
      "In Mantra i ruoli di campo non si deducono dalla posizione: scegli almeno un ruolo.",
    primaryBadge: "principale",
    priceLabel: "Prezzo (facoltativo)",
    priceHint: "Se lasci vuoto, il prezzo registrato non cambia. Un nuovo giocatore resta senza prezzo.",
    priceClear: "Rimuovi il prezzo registrato",
    priceClearHint: "Invia esplicitamente «nessun prezzo» e cancella quello salvato.",
    submitRoster: "Aggiungi alla rosa",
    submitMarket: "Aggiungi al listone",
    submitting: "Aggiungo…",
    added: (name: string) => `${name} aggiunto.`,
    addedSession: "Aggiunti in questa sessione",
    duplicateNote: "Se il giocatore è già presente, aggiorniamo la voce esistente.",
    capacityTitle: "La lega non ha posto",
    invalidPrice: "Prezzo non valido: usa un numero come 12,5.",
    newOpponentNameLabel: "Nome della nuova squadra avversaria",
    targetTeam: "Squadra di destinazione",
  },

  forma: {
    board: "Forma recente",
    intro: "Le ultime partite osservate del giocatore, non quelle del club.",
    empty: "Nessuna partita osservata nello storico coperto.",
    minutes: "min",
    started: "titolare",
    benched: "subentrato",
    home: "casa",
    away: "trasferta",
    rating: "voto osservato",
    noRating: "voto non rilevato",
    goals: "gol",
    assists: "assist",
    shots: "tiri",
    provenance: "Provenienza dei dati",
    observedAt: "osservazione",
    availableAt: "disponibile dal",
    ingestedAt: "acquisito il",
    asOf: "Storico disponibile al",
    dataCutoff: "Ultima pubblicazione usata",
    chartTitle: "Minuti giocati",
    chartDirection: "dalla partita più vecchia alla più recente",
    listDirection: "dalla più recente",
    chartRef: "90′",
    sourcePriority: "priorità",
    coveredFields: "Campi coperti",
    fullIds: "Identificativi completi",
    statId: "Statistica",
    sourceId: "Fonte (ID)",
    recordId: "Record d'origine",
    ingestionRun: "Ciclo di acquisizione",
    schemaVersion: "Versione dello schema",
    adapter: "Adattatore",
    fieldProvenance: "Provenienza per campo",
    missingSource: "record della fonte non presente nella risposta",
    dateOnlyEvent: "Orario dell'evento non disponibile: l'istante registrato rappresenta la sola data.",
    fieldNames: {
      team: "squadra",
      opponent: "avversaria",
      minutes: "minuti",
      started: "titolare",
      goals: "gol",
      assists: "assist",
      shots: "tiri",
      xg: "xG",
      xa: "xA",
      base_rating: "voto osservato",
      is_home: "casa/trasferta",
      kickoff_at: "calcio d'inizio",
      matchweek: "giornata",
    } as Record<string, string>,
  },

  outlook: {
    board: "Prospettiva nella tua lega",
    scoreLabel: "Punti attesi alla prossima partita",
    scoreHint: "Media dei punti calcolata con le regole attive della lega. Non indica la probabilità di giocare.",
    horizon: "Partite",
    computing: "Calcolo la prospettiva",
    computingBody:
      "Applico le regole della lega agli scenari delle prossime partite.",
    fixtureRange: "forbice",
    median: "mediana",
    scoringAppearance: "Voto probabile",
    scoringAppearanceHint:
      "Probabilità di giocare abbastanza minuti da prendere voto secondo le regole della lega.",
    presence: "In campo",
    starter: "Titolare",
    minutes: "Minuti attesi",
    cleanSheetHint:
      "Almeno 60 minuti giocati e nessun gol subito dalla squadra.",
    reasons: "Perché",
    advanced: "Dettagli del modello",
    rulesVersion: "Regole",
    scoringRole: "Ruolo di punteggio",
    roles: "Ruoli di lega",
    seed: "Seme",
    simulations: "Scenari",
    run: "Serie di previsione",
    models: "Modelli",
    statCutoff: "Dati statistici al",
    predictionCutoff: "Cutoff delle previsioni",
    decisionCutoff: "Disponibilità al",
    timezoneLabel: "Fuso orario",
    rawBoard: "Previsioni grezze del modello",
    rawIntro:
      "Valori congelati per bersaglio calcistico, senza le regole della lega e senza le disponibilità aggiornate.",
    unavailableTitle: "Prospettiva non disponibile",
  },

  mercato: {
    title: "Mercato",
    intro: "Confronta gli svincolati con la tua rosa e misura il cambio migliore.",
    horizon: "Orizzonte",
    horizonHint: (n: number) =>
      n === 1 ? "la prossima partita" : `le prossime ${n} partite`,
    horizonNote:
      "L'orizzonte conta le prossime partite di ciascun giocatore, non le giornate ufficiali del calendario.",
    compute: "Calcola i consigli",
    computing: "Sto valutando il mercato",
    computingBody:
      "Provo gli acquisti sulla tua rosa completa, partita per partita. A freddo può richiedere circa un minuto.",
    recompute: "Ricalcola",
    recoverPrice: "Considera il recupero del prezzo di chi esce",
    budget: "Crediti residui",
    budgetUnknown: "Crediti residui non indicati",
    resultsBoard: "Acquisti consigliati",
    in: "Dentro",
    out: "Fuori",
    askingPrice: "richiesta",
    priceUnknown: "prezzo non disponibile",
    affordabilityUnknown: "sostenibilità da verificare",
    improvement: "miglioramento atteso",
    improvementAt: (n: number) =>
      n === 1 ? "sulla prossima partita" : `sulle prossime ${n} partite`,
    horizonTable: "Miglioramento per orizzonte",
    formation: "Modulo",
    formationChange: (before: string, after: string) =>
      before === after
        ? `modulo confermato ${before}`
        : `modulo da ${before} a ${after}`,
    valueOverReplacement: "Valore sul sostituto",
    budgetEfficiency: "Resa per credito",
    roleFlex: "Flessibilità di ruolo",
    schedule: "Moduli partita per partita",
    scheduleBefore: "prima",
    scheduleAfter: "dopo",
    emptyTitle: "Nessun consiglio calcolato",
    emptyBody:
      "Importa il listone degli svincolati con i prezzi, poi calcola i consigli per la tua rosa.",
    importCta: "Importa gli svincolati",
    noMarketTitle: "Listone vuoto",
    noMarketBody:
      "Non ci sono giocatori disponibili sul mercato della lega. Importa il listone degli svincolati per avere consigli.",
    noItems:
      "Nessun acquisto tra quelli valutati migliora la rosa in questo orizzonte.",
    evidenceNote: "I consigli confrontano scenari possibili. Non garantiscono il risultato.",
  },

  giocatori: {
    title: "Giocatori",
    listBoard: "Elenco",
    cardBoard: "Scheda",
    searchLabel: "Cerca un giocatore",
    searchPlaceholder: "Nome del giocatore…",
    onlyActive: "Solo in attività",
    results: (n: number) =>
      n === 1 ? "1 giocatore" : `${n.toLocaleString("it-IT")} giocatori`,
    noResultsTitle: "Nessun giocatore trovato",
    noResultsBody:
      "Nessun nome corrisponde alla ricerca. Prova con una parte del cognome.",
    prev: "Precedenti",
    next: "Successivi",
    pageOf: (from: number, to: number, total: number) =>
      `da ${from} a ${to} di ${total.toLocaleString("it-IT")}`,
    position: "Ruolo",
    team: "Squadra",
    active: "In attività",
    notActive: "Non in attività",
    detailPredictions: "Prossime partite",
    kickoff: "Calcio d'inizio",
    kickoffTimeUnknown: "orario non disponibile",
    matchweek: (n: number) => `Giornata ${n}`,
    presence: "In campo",
    starter: "Titolare",
    minutes: "Minuti attesi",
    goal: "Gol",
    goals: "Gol attesi",
    assist: "Assist",
    assists: "Assist attesi",
    cleanSheet: "Porta inviolata",
    saves: "Parate attese",
    conceded: "Gol subiti attesi",
    cards: "Cartellini",
    yellow: "Giallo",
    red: "Rosso",
    penaltyInvolvement: "Coinvolgimento sui rigori",
    teamGoals: "Gol squadra attesi",
    teamConceded: "Gol subiti squadra",
    range: "forbice",
    reliability: "affidabilità",
    advancedTable: "Tutti i valori del modello",
    target: "Voce",
    expected: "Stima",
    median: "Mediana",
    probability: "Probabilità",
    model: "Modello",
    predictionRun: "Serie di previsione",
    noPredictionsTitle: "Nessuna previsione",
    noPredictionsBodyFresh:
      "Per questo giocatore non ci sono previsioni sulle prossime partite: potrebbe non avere una squadra in Serie A.",
    noPredictionsBodyStale: "I dati non sono aggiornati. Genera le previsioni in Lega, sezione Sistema.",
    born: "Nato il",
    nationality: "Nazionalità",
    foot: "Piede",
    height: "Altezza",
    backToList: "Tutti i giocatori",
    positionNames: {
      GK: "Portiere",
      DEF: "Difensore",
      MID: "Centrocampista",
      FWD: "Attaccante",
    } as Record<string, string>,
  },

  lega: {
    title: "Lega",
    infoBoard: "La lega",
    nameLabel: "Nome",
    renameSaved: "Nome aggiornato.",
    modeLabel: "Modalità",
    modeLocked: "La modalità non si può cambiare dopo la creazione.",
    timezoneLabel: "Fuso orario",
    h2hLabel: "Scontri testa a testa",
    h2hOn: "Attivi",
    h2hOff: "Disattivi",
    h2hSaved: "Impostazione salvata.",
    teamsBoard: "Squadre",
    yourTeam: "La tua squadra",
    opponent: "Avversaria",
    credits: "crediti",
    creditsUnknown: "crediti non indicati",
    importOpponent: "Importa rosa avversaria",
    addOpponent: "Aggiungi avversaria",
    addOpponentManual: "Aggiungi a mano",
    budgetBoard: "Budget",
    budgetHint:
      "Aggiorna i crediti residui dopo ogni operazione fatta in lega. Non serve reimportare la rosa.",
    updatedAt: "Aggiornato",
    rulesBoard: "Regole",
    rulesVersion: (v: number) => `versione ${v}`,
    rulesEffective: "in vigore dal",
    scoring: "Punteggi",
    formations: "Moduli",
    substitutionRules: "Sostituzioni",
    benchSize: "Panchina",
    benchSizeHint: "Lascia vuoto per non impostare un limite. Altrimenti usa un intero da 0 a 50.",
    maxSubs: "Cambi massimi",
    maxSubsHint: "Un numero intero da 0 a 11.",
    appearanceMinutesHint: "Un numero intero da 0 a 130.",
    formationChangeAllowed: "Cambio modulo dalla panchina",
    yes: "Sì",
    no: "No",
    rosterConstraints: "Vincoli di rosa",
    minPlayers: "Giocatori minimi",
    maxPlayers: "Giocatori massimi",
    editRules: "Modifica i punteggi",
    rulesSaveTitle: "Sostituire le regole?",
    rulesSaveBody:
      "Le nuove regole diventano una nuova versione e valgono per i prossimi calcoli. Le versioni precedenti restano archiviate.",
    rulesSaved: "Regole aggiornate.",
    scoringFields: {
      goalGK: "Gol del portiere",
      goalDEF: "Gol del difensore",
      goalMID: "Gol del centrocampista",
      goalFWD: "Gol dell'attaccante",
      assist: "Assist",
      cleanSheetGK: "Porta inviolata (portiere)",
      cleanSheetDEF: "Porta inviolata (difensore)",
      concededGK: "Gol subito (portiere)",
      penaltySaved: "Rigore parato",
      penaltyMissed: "Rigore sbagliato",
      ownGoal: "Autogol",
      yellow: "Ammonizione",
      red: "Espulsione",
      save: "Parata",
      baseRating: "Voto base attivo",
      baseRatingFallback: "Voto base di riserva",
      appearanceMinutes: "Minuti minimi per il voto",
    },
    advancedRules: "Impostazioni avanzate",
    formationsSection: "Moduli",
    formationsHint:
      "Ogni modulo ha nome unico e undici posti validi per la modalità, con un solo portiere.",
    formationClassicHint: "Il portiere è fisso: si contano i 10 di movimento.",
    formationName: "Nome del modulo",
    formationSlots: "Posti",
    formationAdd: "Aggiungi modulo",
    formationRemove: "Rimuovi modulo",
    formationDefaults: "Usa i moduli predefiniti della modalità",
    formationDefaultsHint:
      "I moduli personalizzati vengono scartati e tornano quelli standard.",
    formationCounts: (def: number, mid: number, fwd: number) =>
      `${def}-${mid}-${fwd}`,
    formationSlotLabel: (index: number) => `Posto ${index}`,
    formationsAtLeastOne: "Serve almeno un modulo.",
    formationEleven: "Ogni modulo deve avere esattamente 11 posti.",
    constraintsSection: "Vincoli di rosa",
    constraintsHint:
      "Conteggi per giocatori unici: un multiruolo occupa un solo posto compatibile, assegnato dal server.",
    minPlayersLabel: "Giocatori minimi",
    minPlayersHint: "0 = nessun minimo aggiuntivo.",
    maxPlayersLabel: "Giocatori massimi",
    maxPlayersHint: "Lascia vuoto per non impostare un limite. Altrimenti inserisci almeno 11.",
    roleLimitsLabel: "Posti massimi per ruolo",
    roleLimitsHint: "Lascia vuoto per non impostare un limite. Usa 0 per escludere il ruolo.",
    minAboveMax: "Il minimo non può superare il massimo.",
    modifierSection: "Modificatore difensivo",
    modifierEnabled: "Modificatore attivo",
    modifierRoles: "Ruoli calcistici considerati",
    modifierRolesHint:
      "Si usano i ruoli calcistici (P, D, C, A) anche nelle leghe Mantra.",
    modifierRolesRequired: "Con il modificatore attivo serve almeno un ruolo.",
    modifierReactivateHint: "Riattiva il modificatore per correggere o rimuovere le fasce.",
    modifierBands: "Fasce",
    modifierBandsHint: "Inserisci soglie uniche e crescenti da 0 a 10. I punti possono essere negativi.",
    bandThreshold: "Media minima",
    bandPoints: "Punti",
    bandAdd: "Aggiungi fascia",
    bandRemove: "Rimuovi fascia",
    bandsAscending: "Le soglie devono essere uniche e crescenti.",
    rosterInvalidTitle: "Rosa non valida con le regole attuali",
    rosterInvalidRulesNote:
      "Le regole non cancellano i giocatori: correggi la rosa o i vincoli.",
    seeRoster: "Vedi la mia rosa",
    systemBoard: "Sistema",
    systemHealthy: "Operativo",
    systemUpdating: "Aggiornamento in corso",
    systemDegraded: "Degradato",
    freshnessIngestion: "Ultimo aggiornamento dati",
    freshnessPrediction: "Ultime previsioni",
    freshnessTraining: "Ultimo addestramento",
    never: "mai",
    championModels: "Modelli attivi",
    upcomingFixtures: "Partite in calendario",
    qualityIssues: "Segnalazioni di qualità aperte",
    sources: "Fonti dati",
    sourceStates: {
      available: "attiva",
      stale: "non aggiornata",
      failed: "in errore",
      unconfigured: "non configurata",
      unavailable: "non disponibile",
    } as Record<string, string>,
    lastIngestion: "ultimo dato",
    jobsBoard: "Operazioni",
    refreshData: "Aggiorna i dati",
    refreshDataBody:
      "Scarica gli ultimi risultati e calendari dalle fonti configurate. Può richiedere diversi minuti.",
    trainModels: "Rigenera le previsioni",
    trainModelsBody:
      "Riaddestra i modelli e genera le previsioni per le prossime partite. Può richiedere molti minuti.",
    jobQueued: "in coda",
    jobRunning: "in corso",
    jobSucceeded: "completata",
    jobFailed: "fallita",
    jobCancelled: "annullata",
    jobProgress: "avanzamento",
    jobStarted: "Operazione avviata.",
    jobError: "Errore",
    activeJobs: (queued: number, running: number) =>
      `${running} in corso, ${queued} in coda`,
  },

  errors: {
    validation: "Alcuni campi non sono validi.",
    notFound: "Elemento non trovato.",
    conflictFallback:
      "L'operazione non è possibile nello stato attuale della lega.",

    known: {
      noRoster: {
        match: ["has no active roster"],
        title: "Manca la rosa",
        body: "La squadra selezionata non ha una rosa attiva.",
        cta: "Importa la rosa",
        to: "/rosa/importa",
      },
      noPredictions: {
        match: [
          "no predicted players",
          "need predictions",
          "prediction run",
          "predictions are not available",
        ],
        title: "Previsioni non disponibili",
        body: "Le previsioni non coprono la richiesta. Rigenerale in Lega, sezione Sistema.",
        cta: "Vai al sistema",
        to: "/lega#sistema",
      },
      noMarket: {
        match: ["market has no available players"],
        title: "Listone vuoto",
        body: "Non ci sono giocatori disponibili sul mercato della lega.",
        cta: "Importa gli svincolati",
        to: "/mercato/importa",
      },
      h2hDisabled: {
        match: ["head-to-head recommendations are disabled"],
        title: "Testa a testa disattivo",
        body: "Gli scontri diretti sono disattivati nelle impostazioni della lega.",
        cta: "Apri le impostazioni",
        to: "/lega",
      },
      noLegalFormation: {
        match: [
          "cannot fill any configured legal formation",
          "legal formation is required",
          "no legal lineup",
        ],
        title: "Nessuna formazione schierabile",
        body: "Con i ruoli attuali la rosa non riempie nessun modulo previsto dalle regole.",
        cta: "Vedi la rosa",
        to: "/rosa",
      },
      noRules: {
        match: ["no active scoring rules"],
        title: "Regole mancanti",
        body: "La lega non ha regole di punteggio attive.",
        cta: "Apri le regole",
        to: "/lega",
      },
      sameOpponent: {
        match: ["opponent must be a different fantasy team"],
        title: "Avversario non valido",
        body: "Scegli una squadra avversaria diversa dalla tua.",
        cta: null,
        to: null,
      },
      incompatibleModels: {
        match: ["incompatible", "model"],
        title: "Modelli non allineati",
        body: "Le previsioni non sono allineate ai modelli attuali. Rigenerale in Lega, sezione Sistema.",
        cta: "Vai al sistema",
        to: "/lega#sistema",
      },
    },
  },
} as const;

export type Strings = typeof it;
